### ISSUE TITLE
Road map

### ISSUE THREAD

**Issue by Santhusha-bit** [Santhusha-bit/Unity_intellihack3#1]
#1 Finding a beeter Dataset
#2 Web App Implementation
#3

**Comment by SasikaA073** [comment]
## 1. Finding  a dataset 
## 2. Creating web app
## 3. Create and train model
## 4. Integration of model and web app
## 5. Debugging and testing
## 6. Preparation for presentation

**Comment by chathura-de-silva** [comment]
**Datasets and Algorithms -** 
_https://www.kaggle.com/datasets/csafrit2/maternal-health-risk-data
https://www.kaggle.com/code/bjoernjostein/predicting-health-risks-for-pregnant-patients
https://www.kaggle.com/code/yasserhessein/classification-maternal-health-5-algorithms-ml_

**Comment by SasikaA073** [comment]
done!!!
